import "./globals.css";
import Navbar from "./components/Navbar/index.jsx";
import Footer from "./components/Footer/index.jsx";
import { Montserrat, Barlow_Condensed, Zilla_Slab } from "next/font/google";


const barlow = Barlow_Condensed({
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-barlow",
  subsets: ["latin"],
  display: "swap",
});

const mont = Montserrat({
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-mont",
  subsets: ["latin"],
  display: "swap",
});

const zilla = Zilla_Slab({
  weight: ["400", "700"],
  variable: "--font-zilla",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  
  return (
    <html
      data-theme="coffee"
      lang="en"
      className={`${mont.variable} ${barlow.variable} ${zilla.variable}`}
    >
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
